---@type string[]
KETHO_DOC_SCRIPT_TYPES = {
    'OnAnimFinished',
    'OnChar',
    'OnClick',
    'OnColorSelect',
    'OnCursorChanged',
    'OnDoubleClick',
    'OnDragStart',
    'OnDragStop',
    'OnEditFocusGained',
    'OnEditFocusLost',
    'OnEnter',
    'OnEnterPressed',
    'OnEscapePressed',
    'OnEvent',
    'OnHide',
    'OnHorizontalScroll',
    'OnHyperlinkClick',
    'OnHyperlinkEnter',
    'OnHyperlinkLeave',
    'OnInputLanguageChanged',
    'OnKeyDown',
    'OnKeyUp',
    'OnLeave',
    'OnLoad',
    'OnMessageScrollChanged',
    'OnMouseDown',
    'OnMouseUp',
    'OnMouseWheel',
    'OnMovieFinished',
    'OnMovieHideSubtitle',
    'OnMovieShowSubtitle',
    'OnReceiveDrag',
    'OnScrollRangeChanged',
    'OnShow',
    'OnSizeChanged',
    'OnSpacePressed',
    'OnTabPressed',
    'OnTextChanged',
    'OnTextSet',
    'OnTooltipAddMoney',
    'OnTooltipCleared',
    'OnTooltipSetDefaultAnchor',
    'OnUpdate',
    'OnUpdateModel',
    'OnValueChanged',
    'OnVerticalScroll',
}

---@type string[]
KETHO_DOC_FRAMEXML_METHODS = {
    'AddDoubleLine',
    'AddFontStrings',
    'AddHistoryLine',
    'AddLine',
    'AddMessage',
    'AdvanceTime',
    'AppendText',
    'AtBottom',
    'AtTop',
    'CanNonSpaceWrap',
    'CanSaveTabardNow',
    'Clear',
    'ClearAllPoints',
    'ClearFocus',
    'ClearFog',
    'ClearLines',
    'ClearModel',
    'Click',
    'CopyFontObject',
    'CreateFontString',
    'CreateTexture',
    'CreateTitleRegion',
    'CycleVariation',
    'Disable',
    'DisableDrawLayer',
    'Dress',
    'Enable',
    'EnableDrawLayer',
    'EnableKeyboard',
    'EnableMouse',
    'EnableMouseWheel',
    'FadeOut',
    'GetAlpha',
    'GetAltArrowKeyMode',
    'GetAnchorType',
    'GetBackdrop',
    'GetBackdropBorderColor',
    'GetBackdropColor',
    'GetBlendMode',
    'GetBlinkSpeed',
    'GetBottom',
    'GetButtonState',
    'GetCenter',
    'GetChecked',
    'GetCheckedTexture',
    'GetChildren',
    'GetColorHSV',
    'GetColorRGB',
    'GetColorValueTexture',
    'GetColorValueThumbTexture',
    'GetColorWheelTexture',
    'GetColorWheelThumbTexture',
    'GetCurrentLine',
    'GetCurrentScroll',
    'GetDisabledCheckedTexture',
    'GetDisabledFontObject',
    'GetDisabledTextColor',
    'GetDisabledTexture',
    'GetDrawLayer',
    'GetEffectiveScale',
    'GetFacing',
    'GetFadeDuration',
    'GetFading',
    'GetFogColor',
    'GetFogFar',
    'GetFogNear',
    'GetFont',
    'GetFontObject',
    'GetFontString',
    'GetFrameLevel',
    'GetFrameStrata',
    'GetFrameType',
    'GetHeight',
    'GetHighlightFontObject',
    'GetHighlightTextColor',
    'GetHighlightTexture',
    'GetHistoryLines',
    'GetHitRectInsets',
    'GetHorizontalScroll',
    'GetHorizontalScrollRange',
    'GetHyperlinkFormat',
    'GetID',
    'GetInputLanguage',
    'GetInsertMode',
    'GetJustifyH',
    'GetJustifyV',
    'GetLeft',
    'GetLight',
    'GetLowerBackgroundFileName',
    'GetLowerEmblemFileName',
    'GetLowerEmblemTexture',
    'GetMaxBytes',
    'GetMaxLetters',
    'GetMaxLines',
    'GetMaxResize',
    'GetMinMaxValues',
    'GetMinResize',
    'GetModel',
    'GetModelScale',
    'GetName',
    'GetNormalTexture',
    'GetNumber',
    'GetNumChildren',
    'GetNumLetters',
    'GetNumLinesDisplayed',
    'GetNumMessages',
    'GetNumPoints',
    'GetNumRegions',
    'GetObjectType',
    'GetOrientation',
    'GetParent',
    'GetPingPosition',
    'GetPoint',
    'GetPosition',
    'GetPushedTextOffset',
    'GetPushedTexture',
    'GetRegions',
    'GetRight',
    'GetScale',
    'GetScript',
    'GetScrollChild',
    'GetShadowColor',
    'GetShadowOffset',
    'GetSpacing',
    'GetStatusBarColor',
    'GetStatusBarTexture',
    'GetStringWidth',
    'GetTexCoord',
    'GetTexCoordModifiesRect',
    'GetText',
    'GetTextColor',
    'GetTextFontObject',
    'GetTextHeight',
    'GetTextInsets',
    'GetTexture',
    'GetTextWidth',
    'GetThumbTexture',
    'GetTimeVisible',
    'GetTitleRegion',
    'GetTop',
    'GetUpperBackgroundFileName',
    'GetUpperEmblemFileName',
    'GetUpperEmblemTexture',
    'GetValue',
    'GetValueStep',
    'GetVertexColor',
    'GetVerticalScroll',
    'GetVerticalScrollRange',
    'GetWidth',
    'GetZoom',
    'GetZoomLevels',
    'HasScript',
    'Hide',
    'HighlightText',
    'InitializeTabardColors',
    'Insert',
    'IsAutoFocus',
    'IsClampedToScreen',
    'IsDesaturated',
    'IsEnabled',
    'IsFrameType',
    'IsKeyboardEnabled',
    'IsMouseEnabled',
    'IsMouseWheelEnabled',
    'IsMovable',
    'IsMultiLine',
    'IsNumeric',
    'IsObjectType',
    'IsOwned',
    'IsPassword',
    'IsResizable',
    'IsShown',
    'IsToplevel',
    'IsUserPlaced',
    'IsVisible',
    'LockHighlight',
    'Lower',
    'NumLines',
    'PageDown',
    'PageUp',
    'PingLocation',
    'Raise',
    'RefreshUnit',
    'RegisterAllEvents',
    'RegisterEvent',
    'RegisterForClicks',
    'RegisterForDrag',
    'ReplaceIconTexture',
    'Save',
    'ScrollDown',
    'ScrollToBottom',
    'ScrollToTop',
    'ScrollUp',
    'SetAction',
    'SetAllPoints',
    'SetAlpha',
    'SetAlphaGradient',
    'SetAltArrowKeyMode',
    'SetArrowModel',
    'SetAuctionCompareItem',
    'SetAuctionItem',
    'SetAuctionSellItem',
    'SetAutoFocus',
    'SetBackdrop',
    'SetBackdropBorderColor',
    'SetBackdropColor',
    'SetBagItem',
    'SetBlendMode',
    'SetBlinkSpeed',
    'SetBlipTexture',
    'SetButtonState',
    'SetBuybackItem',
    'SetCamera',
    'SetChecked',
    'SetCheckedTexture',
    'SetClampedToScreen',
    'SetColorHSV',
    'SetColorRGB',
    'SetColorValueTexture',
    'SetColorValueThumbTexture',
    'SetColorWheelTexture',
    'SetColorWheelThumbTexture',
    'SetCraftItem',
    'SetCraftSpell',
    'SetDesaturated',
    'SetDisabledCheckedTexture',
    'SetDisabledFontObject',
    'SetDisabledTextColor',
    'SetDisabledTexture',
    'SetDrawLayer',
    'SetFacing',
    'SetFadeDuration',
    'SetFading',
    'SetFocus',
    'SetFogColor',
    'SetFogFar',
    'SetFogNear',
    'SetFont',
    'SetFontObject',
    'SetFontString',
    'SetFrameLevel',
    'SetFrameStrata',
    'SetGradient',
    'SetGradientAlpha',
    'SetHeight',
    'SetHighlightFontObject',
    'SetHighlightTextColor',
    'SetHighlightTexture',
    'SetHistoryLines',
    'SetHitRectInsets',
    'SetHorizontalScroll',
    'SetHyperlink',
    'SetHyperlinkFormat',
    'SetIconTexture',
    'SetID',
    'SetInboxItem',
    'SetInsertMode',
    'SetInventoryItem',
    'SetJustifyH',
    'SetJustifyV',
    'SetLight',
    'SetLootItem',
    'SetLootRollItem',
    'SetMaskTexture',
    'SetMaxBytes',
    'SetMaxLetters',
    'SetMaxLines',
    'SetMaxResize',
    'SetMerchantCompareItem',
    'SetMerchantItem',
    'SetMinimumWidth',
    'SetMinMaxValues',
    'SetMinResize',
    'SetModel',
    'SetModelScale',
    'SetMovable',
    'SetMultiLine',
    'SetNonSpaceWrap',
    'SetNormalTexture',
    'SetNumber',
    'SetNumeric',
    'SetOrientation',
    'SetOwner',
    'SetPadding',
    'SetParent',
    'SetPassword',
    'SetPetAction',
    'SetPlayerBuff',
    'SetPlayerModel',
    'SetPoint',
    'SetPosition',
    'SetPushedTextOffset',
    'SetPushedTexture',
    'SetQuestItem',
    'SetQuestLogItem',
    'SetQuestLogRewardSpell',
    'SetQuestRewardSpell',
    'SetResizable',
    'SetRotation',
    'SetScale',
    'SetScript',
    'SetScrollChild',
    'SetScrollFromBottom',
    'SetSendMailItem',
    'SetSequence',
    'SetSequenceTime',
    'SetShadowColor',
    'SetShadowOffset',
    'SetShapeshift',
    'SetSlot',
    'SetSpacing',
    'SetSpell',
    'SetStatusBarColor',
    'SetStatusBarTexture',
    'SetTalent',
    'SetTexCoord',
    'SetTexCoordModifiesRect',
    'SetText',
    'SetTextColor',
    'SetTextFontObject',
    'SetTextHeight',
    'SetTextInsets',
    'SetTexture',
    'SetThumbTexture',
    'SetTimeVisible',
    'SetToplevel',
    'SetTrackingSpell',
    'SetTradePlayerItem',
    'SetTradeSkillItem',
    'SetTradeTargetItem',
    'SetTrainerService',
    'SetUnit',
    'SetUnitBuff',
    'SetUnitDebuff',
    'SetUserPlaced',
    'SetValue',
    'SetValueStep',
    'SetVertexColor',
    'SetVerticalScroll',
    'SetWidth',
    'SetZoom',
    'Show',
    'StartMoving',
    'StartSizing',
    'StopMovingOrSizing',
    'ToggleInputLanguage',
    'TryOn',
    'Undress',
    'UnlockHighlight',
    'UnregisterAllEvents',
    'UnregisterEvent',
    'UpdateColorByID',
    'UpdateScrollChildRect',
}

---
---@shape WidgetDescription
---@field is_abstract boolean
---@field parents string[]
---@field constructor function|nil
---@field methods string[]

---@param args table
---@return WidgetDescription
local function describe(args)
    return {
        is_abstract = args['is_abstract'] or false,
        parents = args['parents'] or {},
        constructor = args['constructor'] or function(class) return CreateFrame(class, 'KethoTestWidget' .. class) end,
        methods = args['methods'] or {},
    }
end

---@type table<string, WidgetDescription>
KETHO_DOC_FRAME_WIDGET_CLASS_TO_DESCRIPTION = {
    Button = describe({parents = {'Frame'}}),
    CheckButton = describe({parents = {'Button'}}),
    ColorSelect = describe({parents = {'Frame'}}),
    DressUpModel = describe({parents = {'PlayerModel'}}),
    EditBox = describe({parents = {'Frame', 'FontInstance'}}),
    Font = describe({
        parents = {'FontInstance'},
        constructor = CreateFont,
    }),
    FontInstance = describe({
        is_abstract = true,
        parents = {'UIObject'},
        methods = {
            'GetFont',
            'GetFontObject',
            'GetJustifyH',
            'GetJustifyV',
            'GetShadowColor',
            'GetShadowOffset',
            'GetSpacing',
            'GetTextColor',
            'SetFont',
            'SetFontObject',
            'SetJustifyH',
            'SetJustifyV',
            'SetShadowColor',
            'SetShadowOffset',
            'SetSpacing',
            'SetTextColor',
        },
    }),
    FontString = describe({
        parents = {'FontInstance', 'LayeredRegion'},
        constructor = function()
            return CreateFrame('Frame'):CreateFontString()
        end
    }),
    Frame = describe({parents = {'Region'}}),
    GameTooltip = describe({parents = {'GameTooltip'}}),
    LayeredRegion = describe({
        is_abstract = true,
        parents = {'Region'},
        methods = {
            'GetDrawLayer',
            'SetDrawLayer',
            'SetVertexColor',
        },
    }),
    LootButton = describe({parents = {'Button'}}),
    MessageFrame = describe({parents = {'FontInstance', 'Frame'}}),
    Minimap = describe({parents = {'Frame'}}),
    Model = describe({parents = {'Frame'}}),
    PlayerModel = describe({parents = {'Model'}}),
    Region = describe({
        is_abstract = true,
        parents = {'UIObject'},
        methods = {
            'ClearAllPoints',
            'GetBottom',
            'GetCenter',
            'GetHeight',
            'GetLeft',
            'GetNumPoints',
            'GetParent',
            'GetPoint',
            'GetRight',
            'GetTop',
            'GetWidth',
            'Hide',
            'IsShown',
            'IsVisible',
            'SetAllPoints',
            'SetHeight',
            'SetParent',
            'SetPoint',
            'SetWidth',
            'Show',
        },
    }),
    ScrollFrame = describe({parents = {'Frame'}}),
    ScrollingMessageFrame = describe({parents = {'FontInstance', 'Frame'}}),
    SimpleHTML = describe({parents = {'FontInstance', 'Frame'}}),
    Slider = describe({parents = {'Frame'}}),
    StatusBar = describe({parents = {'Frame'}}),
    TabardModel = describe({parents = {'PlayerModel'}}),
    Texture = describe({
        parents = {'LayeredRegion'},
        constructor = function() return CreateFrame('Frame'):CreateTexture() end
    }),
    UIObject = describe({
        is_abstract = true,
        methods = {
            'GetAlpha',
            'GetName',
            'GetObjectType',
            'IsObjectType',
            'SetAlpha',
        },
    })

}
